#!/usr/bin/env bash
curl -XPUT "http://localhost:9200/_ingest/pipeline/nginx" -H "kbn-xsrf: reporting" -H "Content-Type: application/json" -d \
'
{
  "processors": [
    {
      "date": {
        "field": "datetime",
        "formats": [
          "dd/MMM/yyyy:HH:mm:ss Z",
          "yyyy-MM-ddTHH:mm:ss"
        ]
      }
    },
    {
      "uppercase": {
        "field": "method"
      }
    },
    {
      "remove": {
        "field": "datetime"
      }
    },
    {
      "uri_parts": {
        "field": "url",
        "target_field": "request",
        "keep_original": false,
        "remove_if_successful": true,
        "ignore_failure": true
      }
    },
    {
      "gsub": {
        "field": "request.query",
        "pattern": "^.*password.*$",
        "replacement": "REDACTED",
        "ignore_failure": true
      }
    }
  ],
  "on_failure": [
    {
      "append": {
        "field": "tags",
        "value": [
          "pipeline_fail"
        ]
      }
    }
  ]
}
'
