#!/usr/bin/env bash

curl -X PUT http://localhost:8083/connectors/nginx/config -H "Content-Type: application/json" -d \
'{
 "name": "nginx",
 "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
 "connection.url": "http://elastic-01:9200,http://elastic-02:9200,http://elastic-03:9200",
 "tasks.max": "1",
 "topics": "nginx",
 "type.name": "_doc",
 "value.converter": "org.apache.kafka.connect.json.JsonConverter",
 "value.converter.schemas.enable": "false",
 "key.converter": "org.apache.kafka.connect.json.JsonConverter",
 "key.converter.schemas.enable": "false",
 "schema.ignore": "true",
 "key.ignore": "true",
 "errors.deadletterqueue.topic.name": "dlq",
 "errors.deadletterqueue.topic.replication.factor" : "1",
 "errors.deadletterqueue.context.headers.enable": "true",
 "errors.tolerance": "all",
 "behavior.on.malformed.documents": "ignore",
 "transforms": "insertTS,formatTS",
 "transforms.insertTS.type": "org.apache.kafka.connect.transforms.InsertField$Value",
 "transforms.insertTS.timestamp.field": "IngestedTS",
 "transforms.formatTS.type": "org.apache.kafka.connect.transforms.TimestampConverter$Value",
 "transforms.formatTS.format": "yyyy-MM-dd:HH:mm:ss",
 "transforms.formatTS.field": "IngestedTS",
 "transforms.formatTS.target.type": "string"
}'
