#!/usr/bin/env bash

select_random() {
  printf "%s\0" "$@" | shuf -z -n1 | tr -d '\0'
}

MESSAGE_COUNT=${1:-1}
MESSGAE_DELAY=${2:-1}
COUNTER=1

while [ $COUNTER -le $MESSAGE_COUNT ]; do
  TIMESTAMP=$(date '+%d/%b/%Y:%H:%M:%S %z')
  ARRAY_QUERY[0]="username=matthew.hollick&password=kpopfan"
  ARRAY_QUERY[1]="keepalive"
  ARRAY_STATUS[0]="200"
  ARRAY_STATUS[1]="200"
  ARRAY_STATUS[2]="503"
  ARRAY_STATUS[3]="200"
  ARRAY_STATUS[4]="200"
  ARRAY_STATUS[5]="200"
  ARRAY_STATUS[6]="503"
  ARRAY_STATUS[7]="200"
  ARRAY_STATUS[8]="INVALID_JSON"
  ARRAY_STATUS[9]="\"NOT_A_NUMBER\""
  ARRAY_HOST[0]=$(dd if=/dev/urandom bs=4 count=1 2>/dev/null | od -An -tu1 | sed -e 's/^ *//' -e 's/ *$//' -e 's/  */./g')
  ARRAY_HOST[1]=$(curl -s ifconfig.me/ip)

  QUERY=$(select_random "${ARRAY_QUERY[@]}")
  STATUS=$(select_random "${ARRAY_STATUS[@]}")
  HOST=$(select_random "${ARRAY_HOST[@]}")

  echo "\"$HOST\",\"$STATUS\",\"$QUERY\""
  COUNTER=$(($COUNTER+1))
done
